[build]
  base = "frontend-fixed"
  publish = "frontend-fixed/dist/frontend-fixed"
  command = "npm install -g @angular/cli && npm install && ng build --configuration production"

[build.environment]
  NODE_VERSION = "20"
