[build]
  command = "cd frontend-fixed && npm ci && npx ng build --configuration production"
  publish = "frontend-fixed/dist/frontend-fixed"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--legacy-peer-deps"
